name: Schedule

on:
  schedule:
    - cron: "42 5 * * *"
  workflow_dispatch:

jobs:
  run-main:
    uses: apollo13/django-test/.github/workflows/tests.yml@main
    with:
      ref: refs/heads/main
  run-stable-40x:
    uses: apollo13/django-test/.github/workflows/tests.yml@stable/4.0.x
    with:
      ref: refs/heads/stable/4.0.x