name: Schedule

on:
  schedule:
    - cron: "42 5 * * *"
  workflow_dispatch:

jobs:
  XXX:
    runs-on: ubuntu-latest
    steps:
      - name: Output github github.ref
        run: echo ${{ github.ref }}
  run-main:
    uses: ./.github/workflows/tests.yml@main
  run-stable-40x:
    uses: ./.github/workflows/tests.yml@stable/4.0.x
