name: Tests

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
    name: Python ${{ matrix.python-version }}
    steps:
      - run: echo "${{ github.ref }}"
